apiVersion: v1
kind: Service
metadata:
  name: testwithmaven-service
spec:
  type: NodePort
  selector:
    app: testwithmaven
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007 # Optional
